// flow-typed signature: 1ae39652da9d2220855ca53ac4f74cca
// flow-typed version: <<STUB>>/@iteratec/semantic-release-bitbucket_v^1.1.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@iteratec/semantic-release-bitbucket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@iteratec/semantic-release-bitbucket" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@iteratec/semantic-release-bitbucket/@types/Logger" {
  declare module.exports: any;
}

declare module "@iteratec/semantic-release-bitbucket/@types/NextRelease" {
  declare module.exports: any;
}

declare module "@iteratec/semantic-release-bitbucket/@types/SemanticReleaseConfig" {
  declare module.exports: any;
}

declare module "@iteratec/semantic-release-bitbucket/@types/SemanticReleaseContext" {
  declare module.exports: any;
}

declare module "@iteratec/semantic-release-bitbucket/@types/SemanticReleasePlugin" {
  declare module.exports: any;
}

declare module "@iteratec/semantic-release-bitbucket/@types/SemanticReleasePluginConfig" {
  declare module.exports: any;
}

declare module "@iteratec/semantic-release-bitbucket/bitbucketPlugnConfig" {
  declare module.exports: any;
}

declare module "@iteratec/semantic-release-bitbucket/publish/index" {
  declare module.exports: any;
}

declare module "@iteratec/semantic-release-bitbucket/publish/index.spec" {
  declare module.exports: any;
}

declare module "@iteratec/semantic-release-bitbucket/verifyConfig/index" {
  declare module.exports: any;
}

declare module "@iteratec/semantic-release-bitbucket/verifyConfig/index.spec" {
  declare module.exports: any;
}

// Filename aliases
declare module "@iteratec/semantic-release-bitbucket/@types/Logger.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/@types/Logger"
  >;
}
declare module "@iteratec/semantic-release-bitbucket/@types/NextRelease.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/@types/NextRelease"
  >;
}
declare module "@iteratec/semantic-release-bitbucket/@types/SemanticReleaseConfig.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/@types/SemanticReleaseConfig"
  >;
}
declare module "@iteratec/semantic-release-bitbucket/@types/SemanticReleaseContext.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/@types/SemanticReleaseContext"
  >;
}
declare module "@iteratec/semantic-release-bitbucket/@types/SemanticReleasePlugin.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/@types/SemanticReleasePlugin"
  >;
}
declare module "@iteratec/semantic-release-bitbucket/@types/SemanticReleasePluginConfig.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/@types/SemanticReleasePluginConfig"
  >;
}
declare module "@iteratec/semantic-release-bitbucket/bitbucketPlugnConfig.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/bitbucketPlugnConfig"
  >;
}
declare module "@iteratec/semantic-release-bitbucket/index" {
  declare module.exports: $Exports<"@iteratec/semantic-release-bitbucket">;
}
declare module "@iteratec/semantic-release-bitbucket/index.js" {
  declare module.exports: $Exports<"@iteratec/semantic-release-bitbucket">;
}
declare module "@iteratec/semantic-release-bitbucket/publish/index.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/publish/index"
  >;
}
declare module "@iteratec/semantic-release-bitbucket/publish/index.spec.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/publish/index.spec"
  >;
}
declare module "@iteratec/semantic-release-bitbucket/verifyConfig/index.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/verifyConfig/index"
  >;
}
declare module "@iteratec/semantic-release-bitbucket/verifyConfig/index.spec.js" {
  declare module.exports: $Exports<
    "@iteratec/semantic-release-bitbucket/verifyConfig/index.spec"
  >;
}
