// flow-typed signature: 3d14ddf28d66eb7e8e4b38489aa3ede8
// flow-typed version: <<STUB>>/conventional-changelog-ember_v^2.0.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conventional-changelog-ember'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "conventional-changelog-ember" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "conventional-changelog-ember/conventional-changelog" {
  declare module.exports: any;
}

declare module "conventional-changelog-ember/conventional-recommended-bump" {
  declare module.exports: any;
}

declare module "conventional-changelog-ember/parser-opts" {
  declare module.exports: any;
}

declare module "conventional-changelog-ember/writer-opts" {
  declare module.exports: any;
}

// Filename aliases
declare module "conventional-changelog-ember/conventional-changelog.js" {
  declare module.exports: $Exports<
    "conventional-changelog-ember/conventional-changelog"
  >;
}
declare module "conventional-changelog-ember/conventional-recommended-bump.js" {
  declare module.exports: $Exports<
    "conventional-changelog-ember/conventional-recommended-bump"
  >;
}
declare module "conventional-changelog-ember/index" {
  declare module.exports: $Exports<"conventional-changelog-ember">;
}
declare module "conventional-changelog-ember/index.js" {
  declare module.exports: $Exports<"conventional-changelog-ember">;
}
declare module "conventional-changelog-ember/parser-opts.js" {
  declare module.exports: $Exports<"conventional-changelog-ember/parser-opts">;
}
declare module "conventional-changelog-ember/writer-opts.js" {
  declare module.exports: $Exports<"conventional-changelog-ember/writer-opts">;
}
