// flow-typed signature: f56af122d7c0b27436abb685477c75bd
// flow-typed version: <<STUB>>/lottie-react-native_v2.3.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lottie-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "lottie-react-native" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "lottie-react-native/lib/index" {
  declare module.exports: any;
}

declare module "lottie-react-native/lib/LottieView" {
  declare module.exports: any;
}

declare module "lottie-react-native/src/js/index" {
  declare module.exports: any;
}

declare module "lottie-react-native/src/js/LottieView" {
  declare module.exports: any;
}

// Filename aliases
declare module "lottie-react-native/lib/index.js" {
  declare module.exports: $Exports<"lottie-react-native/lib/index">;
}
declare module "lottie-react-native/lib/LottieView.js" {
  declare module.exports: $Exports<"lottie-react-native/lib/LottieView">;
}
declare module "lottie-react-native/src/js/index.js" {
  declare module.exports: $Exports<"lottie-react-native/src/js/index">;
}
declare module "lottie-react-native/src/js/LottieView.js" {
  declare module.exports: $Exports<"lottie-react-native/src/js/LottieView">;
}
