// flow-typed signature: 5906f22075da028fbb16f50a68848619
// flow-typed version: <<STUB>>/react-native-hamburger_v^0.0.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-hamburger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-hamburger" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-native-hamburger/Hamburger" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-native-hamburger/Hamburger.js" {
  declare module.exports: $Exports<"react-native-hamburger/Hamburger">;
}
declare module "react-native-hamburger/index" {
  declare module.exports: $Exports<"react-native-hamburger">;
}
declare module "react-native-hamburger/index.js" {
  declare module.exports: $Exports<"react-native-hamburger">;
}
